spring.application.name=minegocio-api

# === Datasource Neon ===
spring.datasource.url=jdbc:postgresql://ep-snowy-lake-atfco8tg-pooler.c-9.us-east-1.aws.neon.tech/minegocioapp?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_OqaP1dXC9KIl
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Pool (Neon free tier es estricto)
spring.datasource.hikari.maximum-pool-size=2